"""health: 1 operation from bookshelf.postman_collection.json, generated by api-test-gen."""

import pytest
from models import LivenessAndHowManyBooksAreOnTheShelfResponse
from pydantic import TypeAdapter

pytestmark = pytest.mark.health


def test_liveness_and_how_many_books_are_on_the_shelf(client):
    """GET /health: Liveness, and how many books are on the shelf"""
    response = client.request(
        "GET",
        "/health",
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(LivenessAndHowManyBooksAreOnTheShelfResponse).validate_python(response.json())
