"""loans: 1 operation from bookshelf.postman_collection.json, generated by api-test-gen."""

import pytest
from models import LendABookToTheReaderInXReaderResponse
from pydantic import TypeAdapter

pytestmark = pytest.mark.loans


def test_lend_a_book_to_the_reader_in_x_reader(client, auth_headers):
    """POST /loans: Lend a book to the reader in X-Reader"""
    response = client.request(
        "POST",
        "/loans",
        headers={**auth_headers, "x-reader": "reader-42"},
        json={"book_id": 1},
    )
    assert response.status_code == 201, response.text[:300]
    TypeAdapter(LendABookToTheReaderInXReaderResponse).validate_python(response.json())


def test_lend_a_book_to_the_reader_in_x_reader_without_credentials(client):
    """POST /loans: without credentials must be refused"""
    response = client.request(
        "POST",
        "/loans",
        headers={"x-reader": "reader-42"},
        json={"book_id": 1},
    )
    assert response.status_code in (401, 403), response.text[:300]
