"""books: 6 operations from bookshelf.postman_collection.json, generated by api-test-gen."""

import pytest
from models import (
    AddABookResponse,
    BooksOptionallyThoseOfOneAuthorResponse,
    BooksWhoseTitleContainsAPhraseResponse,
    OneBookResponse,
    ReplaceABookResponse,
)
from pydantic import TypeAdapter

pytestmark = pytest.mark.books


def test_books_optionally_those_of_one_author(client):
    """GET /books: Books, optionally those of one author"""
    response = client.request(
        "GET",
        "/books",
        params={"author_id": "1", "limit": "10"},
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(BooksOptionallyThoseOfOneAuthorResponse).validate_python(response.json())


def test_add_a_book(client, auth_headers):
    """POST /books: Add a book"""
    response = client.request(
        "POST",
        "/books",
        headers=auth_headers,
        json={
            "title": "The Dispossessed",
            "author_id": 1,
            "year": 1974,
            "tags": ["novel", "utopia"],
        },
    )
    assert response.status_code == 201, response.text[:300]
    TypeAdapter(AddABookResponse).validate_python(response.json())


def test_add_a_book_without_credentials(client):
    """POST /books: without credentials must be refused"""
    response = client.request(
        "POST",
        "/books",
        json={
            "title": "The Dispossessed",
            "author_id": 1,
            "year": 1974,
            "tags": ["novel", "utopia"],
        },
    )
    assert response.status_code in (401, 403), response.text[:300]


def test_books_whose_title_contains_a_phrase(client):
    """GET /books/search: Books whose title contains a phrase"""
    response = client.request(
        "GET",
        "/books/search",
        params={"q": "dispossessed"},
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(BooksWhoseTitleContainsAPhraseResponse).validate_python(response.json())


def test_one_book(client):
    """GET /books/{book_id}: One book"""
    book_id = "1"
    response = client.request(
        "GET",
        f"/books/{book_id}",
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(OneBookResponse).validate_python(response.json())


def test_replace_a_book(client, auth_headers):
    """PUT /books/{book_id}: Replace a book"""
    book_id = "1"
    response = client.request(
        "PUT",
        f"/books/{book_id}",
        headers=auth_headers,
        json={
            "title": "The Dispossessed",
            "author_id": 1,
            "year": 1974,
            "tags": ["novel", "utopia"],
        },
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(ReplaceABookResponse).validate_python(response.json())


def test_replace_a_book_without_credentials(client):
    """PUT /books/{book_id}: without credentials must be refused"""
    book_id = "1"
    response = client.request(
        "PUT",
        f"/books/{book_id}",
        json={
            "title": "The Dispossessed",
            "author_id": 1,
            "year": 1974,
            "tags": ["novel", "utopia"],
        },
    )
    assert response.status_code in (401, 403), response.text[:300]


def test_remove_a_book_removing_one_that_is_gone_is_still_204(client, auth_headers):
    """DELETE /books/{book_id}: Remove a book; removing one that is gone is still 204"""
    book_id = "5"
    response = client.request(
        "DELETE",
        f"/books/{book_id}",
        headers=auth_headers,
    )
    assert response.status_code == 204, response.text[:300]


def test_remove_a_book_removing_one_that_is_gone_is_still_204_without_credentials(client):
    """DELETE /books/{book_id}: without credentials must be refused"""
    book_id = "5"
    response = client.request(
        "DELETE",
        f"/books/{book_id}",
    )
    assert response.status_code in (401, 403), response.text[:300]
