"""authors: 2 operations from bookshelf.postman_collection.json, generated by api-test-gen."""

import pytest
from models import AllAuthorsResponse, OneAuthorResponse
from pydantic import TypeAdapter

pytestmark = pytest.mark.authors


def test_all_authors(client):
    """GET /authors: All authors"""
    response = client.request(
        "GET",
        "/authors",
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(AllAuthorsResponse).validate_python(response.json())


def test_one_author(client):
    """GET /authors/{author_id}: One author"""
    author_id = "1"
    response = client.request(
        "GET",
        f"/authors/{author_id}",
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(OneAuthorResponse).validate_python(response.json())
