from api_test_gen.cases import Case
from api_test_gen.render import literal, render_module


def test_literal_is_flat_when_it_fits_and_expanded_when_it_does_not():
    assert literal({"a": 1, "b": [True, None, "x"]}) == '{"a": 1, "b": [True, None, "x"]}'
    assert literal("naïve \\ \"quoted\"") == '"naïve \\\\ \\"quoted\\""'
    assert literal(2.5) == "2.5"
    long = {"name": "x" * 60, "tags": ["one", "two", "three"], "nested": {"k": "v" * 40}}
    assert literal(long, indent=8) == (
        "{\n"
        '            "name": "' + "x" * 60 + '",\n'
        '            "tags": ["one", "two", "three"],\n'
        '            "nested": {"k": "' + "v" * 40 + '"},\n'
        "        }"
    )


def case(**overrides):
    base = dict(
        name="test_get_thing", kind="positive", method="GET", path="/things/{id}", doc="GET /things/{id}: One thing",
        path_params={"id": 7}, query={}, headers={}, body=None, body_kind=None, expect="success", expected_status=200,
        validate="Thing", uses_auth=True, skip_reason=None,
    )
    base.update(overrides)
    return Case(**base)


def test_a_module_renders_imports_marker_and_one_function_per_case():
    source = render_module(
        tag="things", marker="things", operations=1, source_name="bookish.yaml", model_names={"Thing": "Thing"},
        cases=[
            case(),
            case(name="test_get_thing_without_credentials", kind="no_credentials", expect="unauthorized",
                 expected_status=None, validate=None, uses_auth=False),
            case(name="test_echo", method="POST", path="/ping", path_params={}, body="hi", body_kind="text",
                 validate=None, expected_status=None, headers={"X-Trace": "abc"}, query={"page-size": 5}),
            case(
                name="test_upload",
                skip_reason="request body is application/octet-stream, which the generator does not produce",
                validate=None, expected_status=None, uses_auth=False,
            ),
            case(name="test_odd", path="/things/{pet-id}", path_params={"pet-id": 3}, query={}, uses_auth=False,
                 validate=None, expected_status=None),
        ],
    )
    assert source.startswith(
        '"""things: 1 operation from bookish.yaml, generated by api-test-gen."""\n'
        "\n"
        "import pytest\n"
        "from models import Thing\n"
        "from pydantic import TypeAdapter\n"
        "\n"
        "pytestmark = pytest.mark.things\n"
        "\n"
        "\n"
        "def test_get_thing(client, auth_headers):\n"
    )
    assert (
        '    """GET /things/{id}: One thing"""\n'
        "    id = 7\n"
        "    response = client.request(\n"
        '        "GET",\n'
        '        f"/things/{id}",\n'
        "        headers=auth_headers,\n"
        "    )\n"
        "    assert response.status_code == 200, response.text[:300]\n"
        "    TypeAdapter(Thing).validate_python(response.json())\n"
    ) in source
    assert "def test_get_thing_without_credentials(client):\n" in source
    assert "    assert response.status_code in (401, 403), response.text[:300]\n" in source
    assert (
        '        params={"page-size": 5},\n'
        '        headers={**auth_headers, "X-Trace": "abc", "Content-Type": "text/plain"},\n'
        '        content="hi",\n'
    ) in source
    assert "    assert 200 <= response.status_code < 300, response.text[:300]\n" in source
    assert (
        '@pytest.mark.skip(reason="request body is application/octet-stream, which the generator does not produce")\n'
        "def test_upload(client):\n"
    ) in source
    assert '    pet_id = 3\n    response = client.request(\n        "GET",\n        f"/things/{pet_id}",\n' in source
    assert source.count("\n\n\ndef ") == 4 and source.count("\n\n\n@pytest.mark.skip") == 1
    assert source.endswith("\n") and not source.endswith("\n\n")


def test_no_validation_means_no_model_imports():
    source = render_module(
        tag="x", marker="x", operations=1, source_name="d.json", model_names={},
        cases=[
            case(validate=None, uses_auth=False, expect="client_error", expected_status=None, kind="missing_parameter")
        ],
    )
    assert "models" not in source and "TypeAdapter" not in source
    assert "    assert 400 <= response.status_code < 500, response.text[:300]\n" in source
