import ast
import warnings

import pytest

from api_test_gen.cases import Case
from api_test_gen.ir import ApiModel, Body, Operation, Parameter, Security, ref_to
from api_test_gen.openapi import load_openapi
from api_test_gen.postman import load_postman
from api_test_gen.render import docstring, literal, render_conftest, render_module, render_readme
from tests.helpers import REPO, ruff_check


def test_literal_is_flat_when_it_fits_and_expanded_when_it_does_not():
    assert literal({"a": 1, "b": [True, None, "x"]}) == '{"a": 1, "b": [True, None, "x"]}'
    assert literal("naïve \\ \"quoted\"") == '"naïve \\\\ \\"quoted\\""'
    assert literal(2.5) == "2.5"
    long = {"name": "x" * 60, "tags": ["one", "two", "three"], "nested": {"k": "v" * 40}}
    assert literal(long, indent=8) == (
        "{\n"
        '            "name": "' + "x" * 60 + '",\n'
        '            "tags": ["one", "two", "three"],\n'
        '            "nested": {"k": "' + "v" * 40 + '"},\n'
        "        }"
    )


def test_a_string_too_wide_for_its_line_is_split_and_keeps_its_value():
    text = 'quoted "text", a backslash \\, a tab\t and naïve accents ' * 6  # escapes land on chunk boundaries
    for indent in (0, 4, 8, 16):
        rendered = literal(text, indent)
        assert rendered.startswith("(\n") and rendered.endswith("\n" + " " * indent + ")")
        assert ast.literal_eval(rendered) == text
        assert all(len(line) <= 100 for line in rendered.splitlines())
    # What stands before the value on its line counts towards the width too.
    assert literal("x" * 90, prefix=20).startswith("(\n") and literal("x" * 90, prefix=5) == '"' + "x" * 90 + '"'
    nested = {"key": "v" * 120, "list": ["w" * 120, 1], "k" * 120: 2}
    rendered = literal(nested, indent=8)
    assert ast.literal_eval(rendered) == nested
    assert rendered.startswith(
        "{\n"
        '            "key": (\n'
        '                "' + "v" * 82 + '"\n'
        '                "' + "v" * 38 + '"\n'
        "            ),\n"
        '            "list": [\n'
        "                (\n"
    )
    assert all(len(line) <= 100 for line in rendered.splitlines())


def test_every_line_of_an_expanded_value_stays_within_the_width():
    # What follows a value on its line counts too: the comma after an item, the `: (` after a key.
    boundary = [
        (["m" * 113], 10, 120, '    "' + "m" * 113 + '",'),  # exactly 120 columns with the comma: stays flat
        (["m" * 114], 10, 120, "    (\n"),  # 121 columns flat: split
        ({"k": "m" * 108}, 10, 120, '    "k": "' + "m" * 108 + '",'),
        ({"k": "m" * 109}, 10, 120, '    "k": (\n'),
        ({"k" * 111: 1}, 10, 120, '    "' + "k" * 111 + '": (\n        1\n    ),'),  # the key fills the line
        ({"k" * 112: 1}, 10, 120, "    (\n"),  # no room left for `: (` behind the key: the key is split
        ({"outer": [{"inner": "m" * 90}, "n" * 200]}, 5, 100, '            "inner": (\n'),
    ]
    for value, prefix, width, expected in boundary:
        rendered = literal(value, prefix=prefix, width=width)
        assert ast.literal_eval(rendered) == value, rendered
        lines = rendered.splitlines()
        assert prefix + len(lines[0]) <= width and all(len(line) <= width for line in lines[1:]), rendered
        assert expected in rendered, rendered


def case(**overrides):
    base = dict(
        name="test_get_thing", kind="positive", method="GET", path="/things/{id}", doc="GET /things/{id}: One thing",
        path_params={"id": 7}, query={}, headers={}, body=None, body_kind=None, expect="success", expected_status=200,
        validate="Thing", uses_auth=True, skip_reason=None,
    )
    base.update(overrides)
    return Case(**base)


def test_a_module_renders_imports_marker_and_one_function_per_case():
    source = render_module(
        tag="things", marker="things", operations=1, source_name="bookish.yaml", model_names={"Thing": "Thing"},
        cases=[
            case(),
            case(name="test_get_thing_without_credentials", kind="no_credentials", expect="unauthorized",
                 expected_status=None, validate=None, uses_auth=False),
            case(name="test_echo", method="POST", path="/ping", path_params={}, body="hi", body_kind="text",
                 validate=None, expected_status=None, headers={"X-Trace": "abc"}, query={"page-size": 5}),
            case(
                name="test_upload",
                skip_reason="request body is application/octet-stream, which the generator does not produce",
                validate=None, expected_status=None, uses_auth=False,
            ),
            case(name="test_odd", path="/things/{pet-id}", path_params={"pet-id": 3}, query={}, uses_auth=False,
                 validate=None, expected_status=None),
        ],
    )
    assert source.startswith(
        '"""things: 1 operation from bookish.yaml, generated by api-test-gen."""\n'
        "\n"
        "import pytest\n"
        "from models import Thing\n"
        "from pydantic import TypeAdapter\n"
        "\n"
        "pytestmark = pytest.mark.things\n"
        "\n"
        "\n"
        "def test_get_thing(client, auth_headers):\n"
    )
    assert (
        '    """GET /things/{id}: One thing"""\n'
        "    id = 7\n"
        "    response = client.request(\n"
        '        "GET",\n'
        '        f"/things/{id}",\n'
        "        headers=auth_headers,\n"
        "    )\n"
        "    assert response.status_code == 200, response.text[:300]\n"
        "    TypeAdapter(Thing).validate_python(response.json())\n"
    ) in source
    assert "def test_get_thing_without_credentials(client):\n" in source
    assert "    assert response.status_code in (401, 403), response.text[:300]\n" in source
    assert (
        '        params={"page-size": 5},\n'
        '        headers={**auth_headers, "X-Trace": "abc", "Content-Type": "text/plain"},\n'
        '        content="hi",\n'
    ) in source
    assert "    assert 200 <= response.status_code < 300, response.text[:300]\n" in source
    assert (
        '@pytest.mark.skip(reason="request body is application/octet-stream, which the generator does not produce")\n'
        "def test_upload(client):\n"
    ) in source
    assert '    pet_id = 3\n    response = client.request(\n        "GET",\n        f"/things/{pet_id}",\n' in source
    assert source.count("\n\n\ndef ") == 4 and source.count("\n\n\n@pytest.mark.skip") == 1
    assert source.endswith("\n") and not source.endswith("\n\n")


def test_no_validation_means_no_model_imports():
    source = render_module(
        tag="x", marker="x", operations=1, source_name="d.json", model_names={},
        cases=[
            case(validate=None, uses_auth=False, expect="client_error", expected_status=None, kind="missing_parameter")
        ],
    )
    assert "models" not in source and "TypeAdapter" not in source
    assert "    assert 400 <= response.status_code < 500, response.text[:300]\n" in source


def test_a_model_named_by_a_non_success_case_is_not_imported(tmp_path):
    source = render_module(
        tag="x", marker="x", operations=1, source_name="d.json", model_names={"Thing": "Thing"},
        cases=[case(kind="missing_field", expect="client_error", expected_status=None, uses_auth=False)],
    )
    assert "models" not in source and "TypeAdapter" not in source
    path = tmp_path / "test_x.py"
    path.write_text(source)
    assert ruff_check(path) == ""


@pytest.mark.parametrize(
    "names, expected",
    [
        (["Pets", "PetTag", "URL", "Thing2", "Thing10"], "URL, Pets, PetTag, Thing2, Thing10"),
        (["Item1", "Item02A"], "Item02A, Item1"),  # a run with a leading zero sorts before one without
        (["Thing02Item", "Thing010Item"], "Thing010Item, Thing02Item"),  # and digit by digit against another
        (["Model2a", "Model020"], "Model020, Model2a"),
    ],
)
def test_model_imports_are_ordered_the_way_ruff_sorts_them(names, expected, tmp_path):
    source = render_module(
        tag="x", marker="x", operations=len(names), source_name="d.json", model_names={name: name for name in names},
        cases=[case(name=f"test_{index}", validate=name, uses_auth=False) for index, name in enumerate(names)],
    )
    path = tmp_path / "test_x.py"
    path.write_text(source)
    assert ruff_check(path) == ""  # ruff's own verdict on the order is the proof; the line below only reads it
    assert f"from models import {expected}\n" in source


def request_arguments(source: str) -> dict[str, dict[str, object]]:
    """Per test: what its client.request(...) call passes and what its path variables hold, read back from the
    source as values; an argument that is not a literal (the auth headers) is left out."""
    found: dict[str, dict[str, object]] = {}
    for function in ast.parse(source).body:
        if not isinstance(function, ast.FunctionDef):
            continue
        arguments: dict[str, object] = {}
        for node in ast.walk(function):
            if isinstance(node, ast.Call) and getattr(node.func, "attr", "") == "request":
                for keyword in node.keywords:
                    try:
                        arguments[str(keyword.arg)] = ast.literal_eval(keyword.value)
                    except ValueError:
                        pass
            elif isinstance(node, ast.Assign) and isinstance(node.value, ast.Constant):
                arguments[node.targets[0].id] = node.value.value
        found[function.name] = arguments
    return found


def test_long_values_render_a_lint_clean_module_and_reach_the_request_unchanged(tmp_path):
    long = "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt " * 4
    body = {"note": long, "k" * 150: 1, "items": [long, 2], "wide": "東京都渋谷区" * 20}
    source = render_module(
        tag="x", marker="x", operations=4, source_name="d.json", model_names={},
        cases=[
            case(name="test_text", method="POST", path="/echo", path_params={}, body=long, body_kind="text",
                 validate=None, expected_status=None, uses_auth=False),
            case(name="test_json", method="POST", path_params={"id": "i" * 150}, query={"q": "東京" * 60},
                 headers={"X-Long": "h" * 150}, body=body, body_kind="json", validate=None, expected_status=None),
            case(name="test_plain_headers", headers={"X-Long": "h" * 150, "X-Short": "s"}, uses_auth=False,
                 validate=None, expected_status=None),
            case(name="test_skipped", skip_reason="r" * 120, validate=None, expected_status=None, uses_auth=False),
        ],
    )
    path = tmp_path / "test_x.py"
    path.write_text(source, encoding="utf-8")
    assert ruff_check(path) == ""
    arguments = request_arguments(source)
    assert arguments["test_text"]["content"] == long
    assert arguments["test_json"]["json"] == body
    assert arguments["test_json"]["params"] == {"q": "東京" * 60}
    assert arguments["test_json"]["id"] == "i" * 150
    assert arguments["test_plain_headers"]["headers"] == {"X-Long": "h" * 150, "X-Short": "s"}
    assert "        headers={\n            **auth_headers,\n" in source
    skip = next(node for node in ast.parse(source).body if isinstance(node, ast.FunctionDef) and node.decorator_list)
    assert ast.literal_eval(skip.decorator_list[0].keywords[0].value) == "r" * 120


def test_docstrings_are_escaped_and_wrapped(tmp_path):
    for text in ['ends "', 'ends ""', 'ends """', 'a\\"', "ends with \\", '"""', '""""', "", 'mid """ and \\ too']:
        assert ast.literal_eval(docstring(text)) == text, text
    docs = {
        "test_quote": 'GET /x: ends with a "quote"',
        "test_escapes": 'GET /x: back\\slash, """ inside, and ""',
        "test_long": "GET /x: " + ("word " * 40).strip(),
        "test_one_word": "GET /x: " + "w" * 200,
        "test_long_path": "GET /" + "p" * 130,
    }
    source = render_module(
        tag="a\\d", marker="a_d", operations=5, source_name='s"""n.yaml', model_names={},
        cases=[
            case(name=name, doc=doc, validate=None, expected_status=None, uses_auth=False) for name, doc in docs.items()
        ],
    )
    path = tmp_path / "test_a_d.py"
    path.write_text(source)
    assert ruff_check(path) == ""
    with warnings.catch_warnings():
        warnings.simplefilter("error")  # an invalid escape sequence would be a SyntaxError here
        module = ast.parse(source)
    assert ast.get_docstring(module, clean=False) == 'a\\d: 5 operations from s"""n.yaml, generated by api-test-gen.'
    functions = {node.name: node for node in module.body if isinstance(node, ast.FunctionDef)}
    for name, doc in docs.items():
        written = ast.get_docstring(functions[name], clean=False)
        assert written is not None and "".join(written.split()) == "".join(doc.split()), name
    assert ast.get_docstring(functions["test_quote"], clean=False) == docs["test_quote"]
    # The summary goes under the head line, and the closing quotes stand on a line of their own.
    assert '    """GET /x:\n    word word' in source and ' word\n    """\n' in source
    assert all(len(line) <= 120 for line in source.splitlines())


def test_a_long_title_and_base_url_keep_the_conftest_lint_clean(tmp_path):
    api = ApiModel(
        title="T" * 60 + ' """ \\ ' + "東京" * 30, version="9", base_url="", operations=(),
        security=Security(kind="apiKey", name="k", header="X-" + "K" * 120),
    )
    markers = [f"marker_{index}" for index in range(40)]
    base_url = "https://" + "h" * 150 + "/v1"
    source = render_conftest(api, source_name="s.yaml", base_url=base_url, markers=markers)
    path = tmp_path / "conftest.py"
    path.write_text(source, encoding="utf-8")
    assert ruff_check(path) == ""
    with warnings.catch_warnings():
        warnings.simplefilter("error")
        module = ast.parse(source)
    assigned = {node.targets[0].id: node.value for node in module.body if isinstance(node, ast.Assign)}
    assert ast.literal_eval(assigned["BASE_URL"].args[1]) == base_url
    assert ast.literal_eval(assigned["MARKERS"]) == markers
    assert ast.get_docstring(module, clean=False).startswith("Fixtures for the suite generated from s.yaml (TTT")


def readme_text(api: ApiModel) -> str:
    """The README generated for `api`, as one line: its paragraphs are hard-wrapped."""
    text = render_readme(
        api, source_name="d.json", summary_lines=["1 operation, 1 test in 1 module."],
        env_lines=["API_BASE_URL=..."], modules=["test_default.py"], out_hint="out",
    )
    return " ".join(text.split())


NEGATIVES = "one negative case per required query or header parameter and per required body field"
NO_NEGATIVES = (
    "This document declares no required query or header parameter and no required field of a JSON body "
    "(a Postman collection never does), so there is no missing-parameter or missing-field negative."
)
REQUIRING = {"type": "object", "required": ["name"], "properties": {"name": {"type": "string"}}}
REQUIRING_NOTHING = {"type": "object", "properties": {"name": {"type": "string"}}}
ID = Parameter(name="id", location="path", required=True, schema={"type": "integer"})


def operation(**overrides) -> Operation:
    base = dict(operation_id="op", method="POST", path="/things/{id}", tag="default", summary="One thing")
    return Operation(**{**base, **overrides})


def json_body(schema: dict, *examples) -> Body:
    return Body(content_type="application/json", schema=schema, required=True, examples=examples)


def api_with(*operations: Operation, schemas: dict | None = None) -> ApiModel:
    return ApiModel(title="T", version="1", base_url="", operations=operations, schemas=schemas or {})


@pytest.mark.parametrize(
    "api, promises_negatives",
    [
        pytest.param(
            api_with(operation(parameters=(ID, Parameter(name="q", location="query", required=True, schema={})))),
            True, id="required query parameter",
        ),
        pytest.param(
            api_with(operation(parameters=(Parameter(name="X-Reader", location="header", required=True, schema={}),))),
            True, id="required header",
        ),
        pytest.param(
            api_with(operation(body=json_body(ref_to("Thing"))), schemas={"Thing": REQUIRING}),
            True, id="required field behind a reference",
        ),
        pytest.param(
            api_with(operation(body=json_body({"allOf": [ref_to("Thing")]})), schemas={"Thing": REQUIRING}),
            True, id="required field of an allOf part",
        ),
        pytest.param(
            api_with(
                operation(
                    parameters=(
                        ID,
                        Parameter(name="q", location="query", required=False, schema={}, examples=("x",)),
                        Parameter(name="X-Trace", location="header", required=False, schema={}, examples=("t",)),
                    ),
                    body=json_body(ref_to("Thing"), {"name": "x"}),
                ),
                schemas={"Thing": REQUIRING_NOTHING},
            ),
            False, id="what a collection yields: path parameters, optional values, a body requiring nothing",
        ),
        pytest.param(
            api_with(operation(body=Body(content_type="multipart/form-data", schema=REQUIRING, required=True))),
            False, id="a form body requiring a field: the operation is written skipped, no negative comes of it",
        ),
        pytest.param(api_with(), False, id="no operations"),
    ],
)
def test_the_readme_promises_negatives_only_where_the_document_declares_something_required(api, promises_negatives):
    text = readme_text(api)
    assert (NEGATIVES in text) is promises_negatives, text
    assert (NO_NEGATIVES in text) is not promises_negatives, text


def test_the_sample_api_documents_render_one_branch_each():
    """The OpenAPI document of the sample API requires parameters and fields; the collection exported from it
    describes the same operations but, like any Postman collection, declares nothing as required."""
    from_document = readme_text(load_openapi(REPO / "sample_api" / "openapi.json"))
    from_collection = readme_text(load_postman(REPO / "sample_api" / "bookshelf.postman_collection.json"))
    assert NEGATIVES in from_document and NO_NEGATIVES not in from_document
    assert NO_NEGATIVES in from_collection and NEGATIVES not in from_collection
