"""Auth: Others: 2 operations from postman-echo.postman_collection.json, generated by api-test-gen."""

import pytest
from models import BasicAuthResponse
from pydantic import TypeAdapter

pytestmark = pytest.mark.auth_others


def test_basic_auth(client, auth_headers):
    """GET /basic-auth: Basic Auth"""
    response = client.request(
        "GET",
        "/basic-auth",
        headers=auth_headers,
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(BasicAuthResponse).validate_python(response.json())


def test_basic_auth_without_credentials(client):
    """GET /basic-auth: without credentials must be refused"""
    response = client.request(
        "GET",
        "/basic-auth",
    )
    assert response.status_code in (401, 403), response.text[:300]


def test_oauth1_0_verify_signature(client):
    """GET /oauth1: OAuth1.0 Verify Signature"""
    response = client.request(
        "GET",
        "/oauth1",
    )
    assert 200 <= response.status_code < 300, response.text[:300]
