"""Request Methods: 5 operations from postman-echo.postman_collection.json, generated by api-test-gen."""

import pytest

pytestmark = pytest.mark.request_methods


def test_get_request(client):
    """GET /get: GET Request"""
    response = client.request(
        "GET",
        "/get",
        params={"test": "123"},
    )
    assert 200 <= response.status_code < 300, response.text[:300]


def test_post_request(client):
    """POST /post: POST Request"""
    response = client.request(
        "POST",
        "/post",
        headers={"Content-Type": "text/plain"},
        content=(
            "Duis posuere augue vel cursus pharetra. In luctus a ex nec pretium. Praesent neque qua"
            "m, tincidunt nec leo eget, rutrum vehicula magna.\nMaecenas consequat elementum elit, "
            "id semper sem tristique et. Integer pulvinar enim quis consectetur interdum volutpat."
        ),
    )
    assert 200 <= response.status_code < 300, response.text[:300]


def test_put_request(client):
    """PUT /put: PUT Request"""
    response = client.request(
        "PUT",
        "/put",
        headers={"Content-Type": "text/plain"},
        content=(
            "Etiam mi lacus, cursus vitae felis et, blandit pellentesque neque. Vestibulum eget nis"
            "i a tortor commodo dignissim.\nQuisque ipsum ligula, faucibus a felis a, commodo eleme"
            "ntum nisl. Mauris vulputate sapien et tincidunt viverra. Donec vitae velit nec metus."
        ),
    )
    assert 200 <= response.status_code < 300, response.text[:300]


def test_patch_request(client):
    """PATCH /patch: PATCH Request"""
    response = client.request(
        "PATCH",
        "/patch",
        headers={"Content-Type": "text/plain"},
        content=(
            "Curabitur auctor, elit nec pulvinar porttitor, ex augue condimentum enim, eget suscipi"
            "t urna felis quis neque.\nSuspendisse sit amet luctus massa, nec venenatis mi. Suspend"
            "isse tincidunt massa at nibh efficitur fringilla. Nam quis congue mi. Etiam volutpat."
        ),
    )
    assert 200 <= response.status_code < 300, response.text[:300]


def test_delete_request(client):
    """DELETE /delete: DELETE Request"""
    response = client.request(
        "DELETE",
        "/delete",
        headers={"Content-Type": "text/plain"},
        content=(
            "Donec fermentum, nisi sed cursus eleifend, nulla tortor ultricies tellus, ut vehicula "
            "orci arcu ut velit. In volutpat egestas dapibus. \nMorbi condimentum vestibulum sapien"
            ". Etiam dignissim diam quis eros lobortis gravida vel lobortis est. Etiam gravida sed."
        ),
    )
    assert 200 <= response.status_code < 300, response.text[:300]
