"""Auth: Digest: 2 operations from postman-echo.postman_collection.json, generated by api-test-gen."""

import pytest
from models import DigestAuthSuccessResponse
from pydantic import TypeAdapter

pytestmark = pytest.mark.auth_digest


def test_digest_auth_request(client):
    """GET /digest-auth: DigestAuth Request"""
    response = client.request(
        "GET",
        "/digest-auth",
    )
    assert 200 <= response.status_code < 300, response.text[:300]


def test_digest_auth_success(client):
    """GET /digest-auth: DigestAuth Success"""
    response = client.request(
        "GET",
        "/digest-auth",
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(DigestAuthSuccessResponse).validate_python(response.json())
