"""Headers: 2 operations from postman-echo.postman_collection.json, generated by api-test-gen."""

import pytest

pytestmark = pytest.mark.headers


def test_request_headers(client):
    """GET /headers: Request Headers"""
    response = client.request(
        "GET",
        "/headers",
    )
    assert 200 <= response.status_code < 300, response.text[:300]


def test_response_headers(client):
    """GET /response-headers: Response Headers"""
    response = client.request(
        "GET",
        "/response-headers",
        params={"Content-Type": "text/html", "Server": "apibin"},
    )
    assert 200 <= response.status_code < 300, response.text[:300]
