"""Utilities: 6 operations from postman-echo.postman_collection.json, generated by api-test-gen."""

import pytest

pytestmark = pytest.mark.utilities


def test_response_status_code(client):
    """GET /status/200: Response Status Code"""
    response = client.request(
        "GET",
        "/status/200",
    )
    assert 200 <= response.status_code < 300, response.text[:300]


def test_streamed_response(client):
    """GET /stream/10: Streamed Response"""
    response = client.request(
        "GET",
        "/stream/10",
    )
    assert 200 <= response.status_code < 300, response.text[:300]


def test_delay_response(client):
    """GET /delay/3: Delay Response"""
    response = client.request(
        "GET",
        "/delay/3",
    )
    assert 200 <= response.status_code < 300, response.text[:300]


def test_get_utf8_encoded_response(client):
    """GET /encoding/utf8: Get UTF8 Encoded Response"""
    response = client.request(
        "GET",
        "/encoding/utf8",
    )
    assert 200 <= response.status_code < 300, response.text[:300]


def test_gzip_compressed_response(client):
    """GET /gzip: GZip Compressed Response"""
    response = client.request(
        "GET",
        "/gzip",
    )
    assert 200 <= response.status_code < 300, response.text[:300]


def test_deflate_compressed_response(client):
    """GET /deflate: Deflate Compressed Response"""
    response = client.request(
        "GET",
        "/deflate",
    )
    assert 200 <= response.status_code < 300, response.text[:300]
