"""Cookies: 3 operations from postman-echo.postman_collection.json, generated by api-test-gen."""

import pytest
from models import DeleteCookiesResponse, GetCookiesResponse, SetCookiesResponse
from pydantic import TypeAdapter

pytestmark = pytest.mark.cookies


def test_set_cookies(client):
    """GET /cookies/set: Set Cookies"""
    response = client.request(
        "GET",
        "/cookies/set",
        params={"foo1": "bar1", "foo2": "bar2"},
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(SetCookiesResponse).validate_python(response.json())


def test_get_cookies(client):
    """GET /cookies: Get Cookies"""
    response = client.request(
        "GET",
        "/cookies",
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(GetCookiesResponse).validate_python(response.json())


def test_delete_cookies(client):
    """GET /cookies/delete: Delete Cookies"""
    response = client.request(
        "GET",
        "/cookies/delete",
        params={"foo1": "", "foo2": ""},
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(DeleteCookiesResponse).validate_python(response.json())
