"""[draft] Auth: OAuth2.0: 2 operations from postman-echo.postman_collection.json, generated by api-test-gen."""

import pytest
from models import Oauth20GetAccessTokenResponse, Oauth20GetResourceResponse
from pydantic import TypeAdapter

pytestmark = pytest.mark.draft_auth_oauth2_0


@pytest.mark.skip(reason="request body is multipart/form-data, which the generator does not produce")
def test_oauth2_0_get_access_token(client):
    """POST /oauth2/token: OAuth2.0 Get Access Token"""
    response = client.request(
        "POST",
        "/oauth2/token",
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(Oauth20GetAccessTokenResponse).validate_python(response.json())


def test_oauth2_0_get_resource(client):
    """GET /oauth2/user/info: OAuth2.0 Get Resource"""
    response = client.request(
        "GET",
        "/oauth2/user/info",
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(Oauth20GetResourceResponse).validate_python(response.json())
