"""user: 7 operations from petstore-openapi3.json, generated by api-test-gen."""

import pytest
from models import LoginUserResponse, User
from pydantic import TypeAdapter

pytestmark = pytest.mark.user


def test_create_user(client):
    """POST /user: Create user."""
    response = client.request(
        "POST",
        "/user",
        json={
            "id": 10,
            "username": "theUser",
            "firstName": "John",
            "lastName": "James",
            "email": "john@email.com",
            "password": "12345",
            "phone": "12345",
            "userStatus": 1,
        },
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(User).validate_python(response.json())


def test_create_users_with_list_input(client):
    """POST /user/createWithList: Creates list of users with given input array."""
    response = client.request(
        "POST",
        "/user/createWithList",
        json=[
            {
                "id": 10,
                "username": "theUser",
                "firstName": "John",
                "lastName": "James",
                "email": "john@email.com",
                "password": "12345",
                "phone": "12345",
                "userStatus": 1,
            },
        ],
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(User).validate_python(response.json())


def test_login_user(client):
    """GET /user/login: Logs user into the system."""
    response = client.request(
        "GET",
        "/user/login",
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(LoginUserResponse).validate_python(response.json())


def test_logout_user(client):
    """GET /user/logout: Logs out current logged in user session."""
    response = client.request(
        "GET",
        "/user/logout",
    )
    assert response.status_code == 200, response.text[:300]


def test_get_user_by_name(client):
    """GET /user/{username}: Get user by user name."""
    username = "string"
    response = client.request(
        "GET",
        f"/user/{username}",
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(User).validate_python(response.json())


def test_update_user(client):
    """PUT /user/{username}: Update user resource."""
    username = "string"
    response = client.request(
        "PUT",
        f"/user/{username}",
        json={
            "id": 10,
            "username": "theUser",
            "firstName": "John",
            "lastName": "James",
            "email": "john@email.com",
            "password": "12345",
            "phone": "12345",
            "userStatus": 1,
        },
    )
    assert response.status_code == 200, response.text[:300]


def test_delete_user(client):
    """DELETE /user/{username}: Delete user resource."""
    username = "string"
    response = client.request(
        "DELETE",
        f"/user/{username}",
    )
    assert response.status_code == 200, response.text[:300]
