"""store: 4 operations from petstore-openapi3.json, generated by api-test-gen."""

import pytest
from models import GetInventoryResponse, Order
from pydantic import TypeAdapter

pytestmark = pytest.mark.store


def test_get_inventory(client, auth_headers):
    """GET /store/inventory: Returns pet inventories by status."""
    response = client.request(
        "GET",
        "/store/inventory",
        headers=auth_headers,
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(GetInventoryResponse).validate_python(response.json())


def test_get_inventory_without_credentials(client):
    """GET /store/inventory: without credentials must be refused"""
    response = client.request(
        "GET",
        "/store/inventory",
    )
    assert response.status_code in (401, 403), response.text[:300]


def test_place_order(client):
    """POST /store/order: Place an order for a pet."""
    response = client.request(
        "POST",
        "/store/order",
        json={"id": 10, "petId": 198772, "quantity": 7, "status": "approved"},
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(Order).validate_python(response.json())


def test_get_order_by_id(client):
    """GET /store/order/{orderId}: Find purchase order by ID."""
    order_id = 1
    response = client.request(
        "GET",
        f"/store/order/{order_id}",
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(Order).validate_python(response.json())


def test_delete_order(client):
    """DELETE /store/order/{orderId}: Delete purchase order by identifier."""
    order_id = 1
    response = client.request(
        "DELETE",
        f"/store/order/{order_id}",
    )
    assert response.status_code == 200, response.text[:300]
