"""pet: 8 operations from petstore-openapi3.json, generated by api-test-gen."""

import pytest
from models import ApiResponse, FindPetsByStatusResponse, FindPetsByTagsResponse, Pet
from pydantic import TypeAdapter

pytestmark = pytest.mark.pet


def test_update_pet(client, auth_headers):
    """PUT /pet: Update an existing pet."""
    response = client.request(
        "PUT",
        "/pet",
        headers=auth_headers,
        json={"name": "doggie", "photoUrls": ["string"], "id": 10},
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(Pet).validate_python(response.json())


def test_update_pet_without_name(client, auth_headers):
    """PUT /pet: without the required body field 'name' must be refused"""
    response = client.request(
        "PUT",
        "/pet",
        headers=auth_headers,
        json={"photoUrls": ["string"], "id": 10},
    )
    assert 400 <= response.status_code < 500, response.text[:300]


def test_update_pet_without_photo_urls(client, auth_headers):
    """PUT /pet: without the required body field 'photoUrls' must be refused"""
    response = client.request(
        "PUT",
        "/pet",
        headers=auth_headers,
        json={"name": "doggie", "id": 10},
    )
    assert 400 <= response.status_code < 500, response.text[:300]


def test_update_pet_without_credentials(client):
    """PUT /pet: without credentials must be refused"""
    response = client.request(
        "PUT",
        "/pet",
        json={"name": "doggie", "photoUrls": ["string"], "id": 10},
    )
    assert response.status_code in (401, 403), response.text[:300]


def test_add_pet(client, auth_headers):
    """POST /pet: Add a new pet to the store."""
    response = client.request(
        "POST",
        "/pet",
        headers=auth_headers,
        json={"name": "doggie", "photoUrls": ["string"], "id": 10},
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(Pet).validate_python(response.json())


def test_add_pet_without_name(client, auth_headers):
    """POST /pet: without the required body field 'name' must be refused"""
    response = client.request(
        "POST",
        "/pet",
        headers=auth_headers,
        json={"photoUrls": ["string"], "id": 10},
    )
    assert 400 <= response.status_code < 500, response.text[:300]


def test_add_pet_without_photo_urls(client, auth_headers):
    """POST /pet: without the required body field 'photoUrls' must be refused"""
    response = client.request(
        "POST",
        "/pet",
        headers=auth_headers,
        json={"name": "doggie", "id": 10},
    )
    assert 400 <= response.status_code < 500, response.text[:300]


def test_add_pet_without_credentials(client):
    """POST /pet: without credentials must be refused"""
    response = client.request(
        "POST",
        "/pet",
        json={"name": "doggie", "photoUrls": ["string"], "id": 10},
    )
    assert response.status_code in (401, 403), response.text[:300]


def test_find_pets_by_status(client, auth_headers):
    """GET /pet/findByStatus: Finds Pets by status."""
    response = client.request(
        "GET",
        "/pet/findByStatus",
        params={"status": "available"},
        headers=auth_headers,
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(FindPetsByStatusResponse).validate_python(response.json())


def test_find_pets_by_status_without_status(client, auth_headers):
    """GET /pet/findByStatus: without the required query parameter 'status' must be refused"""
    response = client.request(
        "GET",
        "/pet/findByStatus",
        headers=auth_headers,
    )
    assert 400 <= response.status_code < 500, response.text[:300]


def test_find_pets_by_status_without_credentials(client):
    """GET /pet/findByStatus: without credentials must be refused"""
    response = client.request(
        "GET",
        "/pet/findByStatus",
        params={"status": "available"},
    )
    assert response.status_code in (401, 403), response.text[:300]


def test_find_pets_by_tags(client, auth_headers):
    """GET /pet/findByTags: Finds Pets by tags."""
    response = client.request(
        "GET",
        "/pet/findByTags",
        params={"tags": ["string"]},
        headers=auth_headers,
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(FindPetsByTagsResponse).validate_python(response.json())


def test_find_pets_by_tags_without_tags(client, auth_headers):
    """GET /pet/findByTags: without the required query parameter 'tags' must be refused"""
    response = client.request(
        "GET",
        "/pet/findByTags",
        headers=auth_headers,
    )
    assert 400 <= response.status_code < 500, response.text[:300]


def test_find_pets_by_tags_without_credentials(client):
    """GET /pet/findByTags: without credentials must be refused"""
    response = client.request(
        "GET",
        "/pet/findByTags",
        params={"tags": ["string"]},
    )
    assert response.status_code in (401, 403), response.text[:300]


def test_get_pet_by_id(client, auth_headers):
    """GET /pet/{petId}: Find pet by ID."""
    pet_id = 1
    response = client.request(
        "GET",
        f"/pet/{pet_id}",
        headers=auth_headers,
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(Pet).validate_python(response.json())


def test_get_pet_by_id_without_credentials(client):
    """GET /pet/{petId}: without credentials must be refused"""
    pet_id = 1
    response = client.request(
        "GET",
        f"/pet/{pet_id}",
    )
    assert response.status_code in (401, 403), response.text[:300]


def test_update_pet_with_form(client, auth_headers):
    """POST /pet/{petId}: Updates a pet in the store with form data."""
    pet_id = 1
    response = client.request(
        "POST",
        f"/pet/{pet_id}",
        headers=auth_headers,
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(Pet).validate_python(response.json())


def test_update_pet_with_form_without_credentials(client):
    """POST /pet/{petId}: without credentials must be refused"""
    pet_id = 1
    response = client.request(
        "POST",
        f"/pet/{pet_id}",
    )
    assert response.status_code in (401, 403), response.text[:300]


def test_delete_pet(client, auth_headers):
    """DELETE /pet/{petId}: Deletes a pet."""
    pet_id = 1
    response = client.request(
        "DELETE",
        f"/pet/{pet_id}",
        headers=auth_headers,
    )
    assert response.status_code == 200, response.text[:300]


def test_delete_pet_without_credentials(client):
    """DELETE /pet/{petId}: without credentials must be refused"""
    pet_id = 1
    response = client.request(
        "DELETE",
        f"/pet/{pet_id}",
    )
    assert response.status_code in (401, 403), response.text[:300]


@pytest.mark.skip(reason="request body is application/octet-stream, which the generator does not produce")
def test_upload_file(client, auth_headers):
    """POST /pet/{petId}/uploadImage: Uploads an image."""
    pet_id = 1
    response = client.request(
        "POST",
        f"/pet/{pet_id}/uploadImage",
        headers=auth_headers,
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(ApiResponse).validate_python(response.json())
