"""books: 6 operations from openapi.json, generated by api-test-gen."""

import pytest
from models import Book, ListBooksResponse, SearchBooksResponse
from pydantic import TypeAdapter

pytestmark = pytest.mark.books


def test_list_books(client):
    """GET /books: Books, optionally those of one author"""
    response = client.request(
        "GET",
        "/books",
        params={"author_id": 1, "limit": 10},
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(ListBooksResponse).validate_python(response.json())


def test_create_book(client, auth_headers):
    """POST /books: Add a book"""
    response = client.request(
        "POST",
        "/books",
        headers=auth_headers,
        json={
            "title": "The Dispossessed",
            "author_id": 1,
            "year": 1974,
            "tags": ["novel", "utopia"],
        },
    )
    assert response.status_code == 201, response.text[:300]
    TypeAdapter(Book).validate_python(response.json())


def test_create_book_without_title(client, auth_headers):
    """POST /books: without the required body field 'title' must be refused"""
    response = client.request(
        "POST",
        "/books",
        headers=auth_headers,
        json={"author_id": 1, "year": 1974, "tags": ["novel", "utopia"]},
    )
    assert 400 <= response.status_code < 500, response.text[:300]


def test_create_book_without_author_id(client, auth_headers):
    """POST /books: without the required body field 'author_id' must be refused"""
    response = client.request(
        "POST",
        "/books",
        headers=auth_headers,
        json={"title": "The Dispossessed", "year": 1974, "tags": ["novel", "utopia"]},
    )
    assert 400 <= response.status_code < 500, response.text[:300]


def test_create_book_without_year(client, auth_headers):
    """POST /books: without the required body field 'year' must be refused"""
    response = client.request(
        "POST",
        "/books",
        headers=auth_headers,
        json={"title": "The Dispossessed", "author_id": 1, "tags": ["novel", "utopia"]},
    )
    assert 400 <= response.status_code < 500, response.text[:300]


def test_create_book_without_credentials(client):
    """POST /books: without credentials must be refused"""
    response = client.request(
        "POST",
        "/books",
        json={
            "title": "The Dispossessed",
            "author_id": 1,
            "year": 1974,
            "tags": ["novel", "utopia"],
        },
    )
    assert response.status_code in (401, 403), response.text[:300]


def test_search_books(client):
    """GET /books/search: Books whose title contains a phrase"""
    response = client.request(
        "GET",
        "/books/search",
        params={"q": "dispossessed"},
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(SearchBooksResponse).validate_python(response.json())


def test_search_books_without_q(client):
    """GET /books/search: without the required query parameter 'q' must be refused"""
    response = client.request(
        "GET",
        "/books/search",
    )
    assert 400 <= response.status_code < 500, response.text[:300]


def test_get_book(client):
    """GET /books/{book_id}: One book"""
    book_id = 1
    response = client.request(
        "GET",
        f"/books/{book_id}",
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(Book).validate_python(response.json())


def test_replace_book(client, auth_headers):
    """PUT /books/{book_id}: Replace a book"""
    book_id = 1
    response = client.request(
        "PUT",
        f"/books/{book_id}",
        headers=auth_headers,
        json={
            "title": "The Dispossessed",
            "author_id": 1,
            "year": 1974,
            "tags": ["novel", "utopia"],
        },
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(Book).validate_python(response.json())


def test_replace_book_without_title(client, auth_headers):
    """PUT /books/{book_id}: without the required body field 'title' must be refused"""
    book_id = 1
    response = client.request(
        "PUT",
        f"/books/{book_id}",
        headers=auth_headers,
        json={"author_id": 1, "year": 1974, "tags": ["novel", "utopia"]},
    )
    assert 400 <= response.status_code < 500, response.text[:300]


def test_replace_book_without_author_id(client, auth_headers):
    """PUT /books/{book_id}: without the required body field 'author_id' must be refused"""
    book_id = 1
    response = client.request(
        "PUT",
        f"/books/{book_id}",
        headers=auth_headers,
        json={"title": "The Dispossessed", "year": 1974, "tags": ["novel", "utopia"]},
    )
    assert 400 <= response.status_code < 500, response.text[:300]


def test_replace_book_without_year(client, auth_headers):
    """PUT /books/{book_id}: without the required body field 'year' must be refused"""
    book_id = 1
    response = client.request(
        "PUT",
        f"/books/{book_id}",
        headers=auth_headers,
        json={"title": "The Dispossessed", "author_id": 1, "tags": ["novel", "utopia"]},
    )
    assert 400 <= response.status_code < 500, response.text[:300]


def test_replace_book_without_credentials(client):
    """PUT /books/{book_id}: without credentials must be refused"""
    book_id = 1
    response = client.request(
        "PUT",
        f"/books/{book_id}",
        json={
            "title": "The Dispossessed",
            "author_id": 1,
            "year": 1974,
            "tags": ["novel", "utopia"],
        },
    )
    assert response.status_code in (401, 403), response.text[:300]


def test_delete_book(client, auth_headers):
    """DELETE /books/{book_id}: Remove a book; removing one that is gone is still 204"""
    book_id = 5
    response = client.request(
        "DELETE",
        f"/books/{book_id}",
        headers=auth_headers,
    )
    assert response.status_code == 204, response.text[:300]


def test_delete_book_without_credentials(client):
    """DELETE /books/{book_id}: without credentials must be refused"""
    book_id = 5
    response = client.request(
        "DELETE",
        f"/books/{book_id}",
    )
    assert response.status_code in (401, 403), response.text[:300]
