"""authors: 2 operations from openapi.json, generated by api-test-gen."""

import pytest
from models import Author, ListAuthorsResponse
from pydantic import TypeAdapter

pytestmark = pytest.mark.authors


def test_list_authors(client):
    """GET /authors: All authors"""
    response = client.request(
        "GET",
        "/authors",
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(ListAuthorsResponse).validate_python(response.json())


def test_get_author(client):
    """GET /authors/{author_id}: One author"""
    author_id = 1
    response = client.request(
        "GET",
        f"/authors/{author_id}",
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(Author).validate_python(response.json())
