"""loans: 1 operation from openapi.json, generated by api-test-gen."""

import pytest
from models import Loan
from pydantic import TypeAdapter

pytestmark = pytest.mark.loans


def test_create_loan(client, auth_headers):
    """POST /loans: Lend a book to the reader in X-Reader"""
    response = client.request(
        "POST",
        "/loans",
        headers={**auth_headers, "x-reader": "reader-42"},
        json={"book_id": 1},
    )
    assert response.status_code == 201, response.text[:300]
    TypeAdapter(Loan).validate_python(response.json())


def test_create_loan_without_x_reader(client, auth_headers):
    """POST /loans: without the required header 'x-reader' must be refused"""
    response = client.request(
        "POST",
        "/loans",
        headers=auth_headers,
        json={"book_id": 1},
    )
    assert 400 <= response.status_code < 500, response.text[:300]


def test_create_loan_without_book_id(client, auth_headers):
    """POST /loans: without the required body field 'book_id' must be refused"""
    response = client.request(
        "POST",
        "/loans",
        headers={**auth_headers, "x-reader": "reader-42"},
        json={},
    )
    assert 400 <= response.status_code < 500, response.text[:300]


def test_create_loan_without_credentials(client):
    """POST /loans: without credentials must be refused"""
    response = client.request(
        "POST",
        "/loans",
        headers={"x-reader": "reader-42"},
        json={"book_id": 1},
    )
    assert response.status_code in (401, 403), response.text[:300]
