"""health: 1 operation from openapi.json, generated by api-test-gen."""

import pytest
from models import Health
from pydantic import TypeAdapter

pytestmark = pytest.mark.health


def test_health(client):
    """GET /health: Liveness, and how many books are on the shelf"""
    response = client.request(
        "GET",
        "/health",
    )
    assert response.status_code == 200, response.text[:300]
    TypeAdapter(Health).validate_python(response.json())
